config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :friendships
  resources :members
  resources :find_experts, only: [:index]
  get '/find_experts/find_experts', to: 'find_experts#find_experts'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
# frozen_string_literal: true

class Friendship < ApplicationRecord
  belongs_to :member
  belongs_to :friend, class_name: 'Member'
end

app/models/heading.rb
# frozen_string_literal: true

class Heading < ApplicationRecord
  belongs_to :member
end

app/models/member.rb
# frozen_string_literal: true

class Member < ApplicationRecord
  has_many :headings
  has_many :friendships
  has_many :members, through: :friendships

  def friends_lists
    Friendship.where(friend: self).or(Friendship.where(member: self))
  end

  def member_friends
    member_friends = []
    friends = friends_lists
    friends.each do |friend|
      member_friends.append(friend.friend) if friend.friend != self
      member_friends.append(friend.member) if friend.member != self
    end
    member_friends
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/find_experts_controller.rb
# frozen_string_literal: true

class FindExpertsController < ApplicationController
  def index
    @members = Member.all
  end

  def find_experts
    member_topic_knowledge = Member.joins(:headings).where("headings.topic LIKE '%#{params[:q]}%'")

    @path = shortest_path_to_member(Member.find(params[:member]), member_topic_knowledge.first)
  end

  def shortest_path_to_member(initial_member, target_member)
    return nil if initial_member.nil? || target_member.nil?

    return nil if initial_member == target_member

    to_visit = []
    shortest_path = {}

    to_visit.append(initial_member)
    shortest_path[initial_member] = nil

    while to_visit
      current_member = to_visit.pop

      break if current_member == target_member

      next if current_member.member_friends.nil?

      current_member.member_friends.each do |friend|
        unless shortest_path.key?(friend)
          to_visit.append(friend)
          shortest_path[friend] = current_member
        end
      end
    end

    return nil if shortest_path[target_member].nil?

    create_path(shortest_path, target_member)
  end

  def create_path(shortest_path, target_member)
    path = []
    curr_member = target_member
    while curr_member
      path.append(curr_member.name)
      curr_member = shortest_path[curr_member]
    end
    path.reverse!
  end
end

app/controllers/friendships_controller.rb
# frozen_string_literal: true

class FriendshipsController < ApplicationController
  before_action :set_friendship, only: %i[show edit update destroy]

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show; end

  # GET /friendships/new
  def new
    @members = Member.all
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit; end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = Friendship.new
    puts params
    @friendship.member_id = params.dig(:friendship, :member).to_i
    @friendship.friend_id = params.dig(:friendship, :friend).to_i

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to @friendship, notice: 'Friendship was successfully created.' }
        format.json { render :show, status: :created, location: @friendship }
      else
        format.html { render :new }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to friendships_url, notice: 'Friendship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friendship
    @friendship = Friendship.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friendship_params
    params.require(:friendship).permit(:member, :friend)
  end
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
  require "shorturl"
  before_action :set_member, only: %i[show edit update destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show; end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit; end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    @member.shortened_url = ShortURL.shorten(@member.personal_website, :tinyurl)
    respond_to do |format|
      if @member.save
        HeadingsUtil.save_headings(@member)
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def member_params
    params.require(:member).permit(:name, :personal_website, :shortned_url)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/friendships_helper.rb
# frozen_string_literal: true

module FriendshipsHelper
end

app/helpers/members_helper.rb
# frozen_string_literal: true

module MembersHelper
end

app/views/find_experts/find_experts.html.erb
<p id="notice"><%= notice %></p>

<p>Path to expert</p>

<%= @path.join('->') %>

app/views/find_experts/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_with(url: "/find_experts/find_experts", method: "get", local: true) do %>

  <%= select_tag('member', options_for_select(@members.map{|member| [member.name, member.id] })) %>

  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>

<% end %>

app/views/friendships/_form.html.erb
<%= form_with(model: friendship, local: true) do |form| %>
  <% if friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
        <% friendship.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :member %>
    <%= form.select 'member' ,options_for_select(@members.map{|member| [member.name, member.id] }) %>
  </div>

  <div class="field">
    <%= form.label :friend %>
    <%= form.select 'friend', options_for_select(@members.map{|member| [member.name, member.id] }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friendships</h1>

<table>
  <thead>
    <tr>
      <th>Member</th>
      <th>Friend</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.member %></td>
        <td><%= friendship.friend %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @friendship.member.name %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend.name %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpertsDirectory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :personal_website %>
    <%= form.text_field :personal_website %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Shortened url</th>
      <th>Number of friends</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= link_to "#{member.shortened_url}", member.shortened_url %></td>
        <td><%= member.friends_lists.size %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Personal website:</strong>
  <%= link_to "#{@member.personal_website}", @member.personal_website %>
</p>

<p>
  <strong>Shortened url:</strong>
  <%= link_to "#{@member.shortened_url}", @member.personal_website %>
</p>

<p>
  <strong>headings:</strong>
  <% @member.headings.each do |heading| %>
  <p>
    <%= heading.topic %>
  </p>

  <% end %>
</p>

<p>
  <strong>Friends pages:</strong>
  <% @member.friends_lists.each do |frienship| %>

    <% if frienship.friend.id != @member.id %>
      <p>
        <%= link_to "#{frienship.friend.name}", "http://0.0.0.0:3000/members/#{frienship.friend.id}" %>
      </p>
    <% end %>

    <% if frienship.member.id != @member.id %>
      <p>
        <%= link_to "#{frienship.member.name}", "http://0.0.0.0:3000/members/#{frienship.member.id}" %>
      </p>
    <% end %>

  <% end %>
</p>





<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>